spring.application.name=chat-app-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/chat_app_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=MySQL@1204
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ReplaceThisWithARandomLongSecretStringAtLeast64CharsForHS256Security
jwt.expiration-ms=86400000

logging.level.root=INFO
logging.level.com.chatapp.backend=DEBUG
logging.level.org.hibernate.SQL=DEBUG